version: "3.3"
services:
  backend:
    image: oven/bun:1.0.3
    restart: always
    working_dir: /app
    volumes:
      - ./backend:/app:ro
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
    command: bun run dev
