version: "3.3"
services:
  db:
    image: mongo:5.0.2
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=at-first-sight
      - MONGO_INITDB_ROOT_PASSWORD=at-first-sight
      - MONGODB_DATABASE=at-first-sight
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  backend:
    image: oven/bun:1.0.4
    restart: always
    working_dir: /app
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    environment:
      - PORT=4000
    command: bun run dev

  tg-web-app:
    image: oven/bun:1.0.4-alpine
    restart: always
    working_dir: /app
    ports:
      - 5173:5173
    volumes:
      - ./tg-web-app:/app
    environment:
      - PORT=5173
      - BACKEND_URL=http://backend:4000
    command: bun run dev

volumes:
  db_data:
