version: "3.3"
services:
  db:
    image: mongo:5.0.2
    restart: always
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - db_data:/data/db
      - ./mongo/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro

  object-storage:
    image: bitnami/minio:latest
    restart: always
    environment:
      - MINIO_ROOT_USER=kundin
      - MINIO_ROOT_PASSWORD=very-secret-password
      - MINIO_SKIP_CLIENT=yes
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio_storage:/data

  imgproxy:
    image: darthsim/imgproxy
    env_file:
      - .env
    environment:
      - IMGPROXY_USE_S3=true
      - IMGPROXY_S3_ENDPOINT=http://object-storage:9000

  backend:
    image: oven/bun:1.0.4
    restart: always
    working_dir: /app
    ports:
      - 4000:4000
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - PORT=4000
      - AWS_ENDPOINT=http://object-storage:9000
    command: bun run dev

  tg-web-app:
    image: oven/bun:1.0.4-alpine
    restart: always
    working_dir: /app
    ports:
      - 5173:5173
    volumes:
      - ./tg-web-app:/app
    env_file:
      - .env
    environment:
      - PORT=5173
      - BACKEND_URL=http://backend:4000
      - IMGPROXY_URL=http://imgproxy:8080
      - AWS_BUCKET=at-first-sight
    command: bun run dev

volumes:
  db_data:
  minio_storage:
